# Generated by Django 3.2.8 on 2021-11-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matiere',
            old_name='currentDuration',
            new_name='dureeEnCour',
        ),
        migrations.RenameField(
            model_name='matiere',
            old_name='dailyDuration',
            new_name='dureeQuotidienne',
        ),
        migrations.RenameField(
            model_name='matiere',
            old_name='totalDuration',
            new_name='dureeTotale',
        ),
        migrations.AlterField(
            model_name='personne',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personne',
            name='fonction',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personne',
            name='mdp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personne',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personne',
            name='prenom',
            field=models.CharField(max_length=255),
        ),
    ]
