# Generated by Django 3.2.8 on 2021-12-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connection', '0002_auto_20211103_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
